language: generic
sudo: true

env:
    global:
          # ECR URL
        - ECR_US_EAST_1_URL="012629307706.dkr.ecr.us-east-1.amazonaws.com"

          # Tag Name
        - LATEST="latest"
services:
    - docker

before_install:
      # ---------------------------------------------------------------
      # BASE IMAGE
      # ---------------------------------------------------------------

      # Install Utils
      # ---------------------------------------------------------------
    - sudo apt-get install  --no-install-recommends tree curl python
    - sudo apt-get clean
    - sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
      
      # AWS Cli
    - sudo pip install awscli

      # Download Oracle - tar from the URL
      # ---------------------------------------------------------------
    - curl -v -j -k -L -H "Cookie:oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/jdk-8u171-linux-x64.tar.gz > ./base/oracle-jdk.tar.gz


      # ---------------------------------------------------------------
      # MAVEN IMAGE
      # ---------------------------------------------------------------
      # 
      # Clone Necessary Repository
    - git clone git@github.com:unbxd/asterix.git maven/projects/asterix
    - git clone git@github.com:unbxd/solr-plugin.git maven/projects/solr-plugin

      # Download Dependencies from S3
    - aws s3 cp s3://unbxd-build-artifacts/solr/solr-plugins/solr-plugin-0.2.3.jar maven/projects/asterix/solr-plugin-latest.jar
    
install:
    - cd ./base && docker build -t oracle-jdk8-base:latest .
    - cd ../maven && docker build -t oracle-jdk8-with-mvn:latest .
