language: generic
sudo: true

env:
    global:
          # ECR URL
        - ECR_US_EAST_1_URL="012629307706.dkr.ecr.us-east-1.amazonaws.com"

          # Tag Name
        - LATEST="latest"

        - PROJECT_DIR="/projects"

        - ASTERIX_DIR="${PROJECT_DIR}/asterix"

services:
    - docker

before_install:

      # Install Utils
      # ---------------------------------------------------------------
    - sudo apt-get install tree curl

      # Download Oracle - tar from the URL
      # ---------------------------------------------------------------
    - curl -v -j -k -L -H "Cookie:oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/jdk-8u171-linux-x64.tar.gz > ./base/oracle-jdk.tar.gz

install:
    - cd ./base && docker build -t oracle-java8-base:latest .
